//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AtumLauncher.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ATUMLAUNCHER_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PRE_IP               131
#define IDB_LOGIN                       158
#define IDD_DIALOG_LOGIN_SUCCESS        183
#define IDB_UPDATE                      195
#define IDB_BACKIMAGE                   210
#define IDB_X                           214
#define IDB_GEAR                        221
#define IDB_SERVERLIST                  222
#define IDB_USECLASS                    223
#define IDB_BARLEFT                     224
#define IDB_BARRIGHT                    225
#define IDB_BARCENTER                   226
#define IDB_GOD                         234
#define IDB_GOBTN                       235
#define IDB_JOINBTN                     240
#define IDB_CENTER                      241
#define IDB_TITLE                       242
#define IDB_SERVERUSER                  247
#define IDB_BG_VTC                      248
#define IDB_GO_VTC                      249
#define IDB_LISTBG_VTC                  250
#define IDB_ICON_VTC                    251
#define IDB_SERVERUSER_VTC              252
#define IDB_GO_S2                       255
#define IDB_GO_CHN                      257
#define IDD_DIALOG1                     259
#define IDD_DLG_SCREEN_KEYBOARD         259
#define IDB_SCREEN_KEYBOARD             260
#define IDB_SCREEN_KEYBOARD_MASK        261
#define IDB_SCREEN_KEYBOARD_ON_SHIFT    262
#define IDB_KEY_1                       263
#define IDB_KEY_2                       264
#define IDB_KEY_3                       265
#define IDB_KEY_4                       266
#define IDB_KEY_5                       267
#define IDB_KEY_6                       268
#define IDB_KEY_7                       269
#define IDB_KEY_8                       270
#define IDB_KEY_9                       271
#define IDB_KEY_0                       272
#define IDB_KEY_q                       273
#define IDB_KEY_w                       274
#define IDB_KEY_e                       275
#define IDB_KEY_r                       276
#define IDB_KEY_t                       277
#define IDB_KEY_y                       278
#define IDB_KEY_u                       279
#define IDB_KEY_i                       280
#define IDB_KEY_o                       281
#define IDB_KEY_p                       282
#define IDB_KEY_a                       283
#define IDB_KEY_s                       284
#define IDB_KEY_d                       285
#define IDB_KEY_f                       286
#define IDB_KEY_g                       287
#define IDB_KEY_h                       288
#define IDB_KEY_j                       289
#define IDB_KEY_k                       290
#define IDB_KEY_l                       291
#define IDB_KEY_z                       292
#define IDB_KEY_x                       293
#define IDB_KEY_c                       294
#define IDB_KEY_v                       295
#define IDB_KEY_b                       296
#define IDB_KEY_n                       297
#define IDB_KEY_m                       298
#define IDB_KEY_1_ON_SHIFT              299
#define IDB_KEY_2_ON_SHIFT              300
#define IDB_KEY_3_ON_SHIFT              301
#define IDB_KEY_4_ON_SHIFT              302
#define IDB_KEY_5_ON_SHIFT              303
#define IDB_KEY_6_ON_SHIFT              304
#define IDB_KEY_7_ON_SHIFT              305
#define IDB_KEY_8_ON_SHIFT              306
#define IDB_KEY_9_ON_SHIFT              307
#define IDB_KEY_0_ON_SHIFT              308
#define IDB_KEY_q_ON_SHIFT              309
#define IDB_KEY_w_ON_SHIFT              310
#define IDB_KEY_e_ON_SHIFT              311
#define IDB_KEY_r_ON_SHIFT              312
#define IDB_KEY_t_ON_SHIFT              313
#define IDB_KEY_y_ON_SHIFT              314
#define IDB_KEY_u_ON_SHIFT              315
#define IDB_KEY_i_ON_SHIFT              316
#define IDB_KEY_o_ON_SHIFT              317
#define IDB_KEY_p_ON_SHIFT              318
#define IDB_KEY_a_ON_SHIFT              319
#define IDB_KEY_s_ON_SHIFT              320
#define IDB_KEY_d_ON_SHIFT              321
#define IDB_KEY_f_ON_SHIFT              322
#define IDB_KEY_g_ON_SHIFT              323
#define IDB_KEY_h_ON_SHIFT              324
#define IDB_KEY_j_ON_SHIFT              325
#define IDB_KEY_k_ON_SHIFT              326
#define IDB_KEY_l_ON_SHIFT              327
#define IDB_KEY_z_ON_SHIFT              328
#define IDB_KEY_x_ON_SHIFT              329
#define IDB_KEY_c_ON_SHIFT              330
#define IDB_KEY_v_ON_SHIFT              331
#define IDB_KEY_b_ON_SHIFT              332
#define IDB_KEY_n_ON_SHIFT              333
#define IDB_KEY_m_ON_SHIFT              334
#define IDB_KEY_BACKSPACE               335
#define IDB_KEY_CAPSLOCK                336
#define IDB_KEY_ENTER                   337
#define IDB_KEY_SHIFT                   338
#define IDB_KEY_SPACE                   339
#define IDB_KEY_CAPSLOCK_ON             340
#define IDB_KEY_SHIFT_ON                341
#define IDB_HOMEPAGE_DOWN               342
#define IDB_HOMEPAGE_FOCUS              343
#define IDB_HOMEPAGE_UP                 344
#define IDB_EDITBG                      346
#define IDB_CB_CHECK                    348
#define IDB_CB_UNCHECK                  349
#define IDB_COMBOBOX                    350
#define IDD_DLG_GUARD_AGREEMENT         351
#define IDB_BG_VTC_MASK                 357
#define IDB_TITLE_MASK                  361
#define IDB_SERVER_LIST_MASK            365
#define IDC_EDIT_ACCOUNT                1002
#define IDC_ACCOUNT                     1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_PASSWORD                    1005
#define IDC_LOGO                        1006
#define IDC_DOWNLOAD_FILENUM            1007
#define IDC_DECA_SERVER                 1008
#define IDC_PROGRESS1                   1009
#define IDC_FILE_UPDATE_GROUP           1010
#define IDC_BATTALUS_SERVER             1011
#define IDC_SHARRINE_SERVER             1012
#define IDC_PHILON_SERVER               1013
#define IDC_STATIC_SERVER_GROUP         1014
#define IDC_EDIT_PRE_IP                 1016
#define IDC_STATIC_PRE_IP               1017
#define IDGO                            1019
#define IDC_EDIT_BIN                    1020
#define IDC_NOTICE                      1020
#define IDC_STATIC_BIN                  1021
#define IDJOIN                          1021
#define IDSECRET                        1022
#define IDC_EDIT_PATH                   1022
#define IDEND                           1023
#define IDC_STATIC_PATH                 1023
#define IDDECA                          1024
#define IDBATTAL                        1025
#define IDSHARIN                        1026
#define IDPHILON                        1027
#define IDC_BUTTON3                     1030
#define IDC_X                           1030
#define IDC_FILE_INFO                   1031
#define IDC_EDIT_CMD_LINE               1032
#define IDC_CLIENT_UPDATE               1033
#define IDC_WINDOW_MODE                 1034
#define IDC_STATIC_WINDOW_DEGREE        1037
#define IDC_LIST                        1038
#define IDC_COMBO                       1045
#define IDC_COMBO_WINDOW_DEGREE_LAUNCHER 1045
#define IDC_COMBO_WINDOW_DEGREE_LAUNCHER2 1046
#define IDCAN                           1048
#define IDC_BUTTON_BIN_SELECT           1049
#define IDMIN                           1049
#define IDC_BUTTON_PATH_SELECT          1050
#define IDC_BTN_HOMEPAGE                1050
#define IDC_COMBO_PRESERVER_IP          1051
#define IDC_COMBO_BIN                   1052
#define IDC_CHARACTER_NAME              1052
#define IDC_COMBO_PATH                  1053
#define IDC_COMBO_SERVER_LIST           1054
#define IDC_BTN_KEY_0                   1055
#define IDC_BTN_KEY_1                   1056
#define IDC_BTN_KEY_2                   1057
#define IDC_BTN_KEY_3                   1058
#define IDC_BTN_KEY_4                   1059
#define IDC_BTN_KEY_5                   1060
#define IDC_BTN_KEY_6                   1061
#define IDC_BTN_KEY_7                   1062
#define IDC_BTN_KEY_8                   1063
#define IDC_BTN_KEY_9                   1064
#define IDC_BTN_KEY_10                  1065
#define IDC_BTN_KEY_11                  1066
#define IDC_BTN_KEY_12                  1067
#define IDC_BTN_KEY_13                  1068
#define IDC_BTN_KEY_14                  1069
#define IDC_BTN_KEY_15                  1070
#define IDC_BTN_KEY_16                  1071
#define IDC_BTN_KEY_17                  1072
#define IDC_BTN_KEY_18                  1073
#define IDC_BTN_KEY_19                  1074
#define IDC_BTN_KEY_20                  1075
#define IDC_BTN_KEY_21                  1076
#define IDC_BTN_KEY_22                  1077
#define IDC_BTN_KEY_23                  1078
#define IDC_BTN_KEY_24                  1079
#define IDC_BTN_KEY_25                  1080
#define IDC_BTN_KEY_26                  1081
#define IDC_BTN_KEY_27                  1082
#define IDC_BTN_KEY_28                  1083
#define IDC_BTN_KEY_29                  1084
#define IDC_BTN_KEY_30                  1085
#define IDC_BTN_KEY_31                  1086
#define IDC_BTN_KEY_32                  1087
#define IDC_BTN_KEY_33                  1088
#define IDC_BTN_KEY_34                  1089
#define IDC_BTN_KEY_35                  1090
#define IDC_BTN_VIEW_SCREEN_KEYBOARD    1093
#define IDC_CHECK_WINDOWS_MODE          1094
#define IDC_CHECK_REMEMBER_ID           1095
#define IDC_BTN_BACKSPACE               1097
#define IDC_EDIT_AGREEMENT_TEXT         1097
#define IDC_BTN_CAPS_LOCK               1098
#define IDC_CHECK_V_SYNC                1098
#define IDC_BTN_SHIFT                   1099
#define IDC_BTN_ENTER                   1100
#define IDC_BTN_SPACE                   1101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        366
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
