//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AtumMonitor.rc
//
#define IDC_BUTTON_CONNECT_SBC          3
#define IDC_BUTTON_CANCEL_SBC           5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_UPDATELISTGENERATOR_DIALOG  102
#define IDD_ZIPFILE_DIALOG              102
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_ATUMMOTYPE                  129
#define IDD_FIELD_SERVER_DLG            130
#define IDD_DIALOG_MAPBLOCKINFO         131
#define IDB_TREE_ICON                   132
#define IDR_TREE_CONTEXT_MENU_NPC       132
#define IDR_TREE_CONTEXT_MENU_FIELD     133
#define IDR_TREE_CONTEXT_MENU_PRE       134
#define IDD_DIALOG_DBG_PARAM            135
#define IDR_TREE_CONTEXT_MENU_IM        136
#define IDD_DLG_NEWSERVERGROUP          137
#define IDR_TREE_CONTEXT_MENU_ROOT      139
#define IDD_DLG_PRE_USER_COUNT          140
#define IDD_INFO_GEN                    141
#define IDD_DIALOG_SQL_READER           142
#define IDD_DIALOG_ADMIN_COMMAND        143
#define IDD_CLIENTFTPUPDATEMANAGER_DIALOG 144
#define IDD_DIALOG_SERVER_DB_CONNECTION 146
#define IDR_MENU_TRAY                   147
#define IDD_DIALOG_SELECT_SERVER        148
#define IDD_DLG_SET_MGAME_EVENT_TYPE    149
#define IDD_DLG_SET_CITYWAR_TIME        151
#define IDD_IMPORT_EXCELFILE            152
#define IDB_BITMAP_CHECK_IMAGE          153
#define IDD_CHECKITEMDIALOG             154
#define IDD_CHECKITEMDIALOG2            155
#define IDC_EDIT1                       1000
#define IDC_EDIT_ROOTDIR                1000
#define IDC_EDIT_FOLDER_TO_ZIP          1000
#define IDC_EDIT_TARGETFILE             1000
#define IDC_EDIT2                       1001
#define IDC_BUTTON_FOLDER_TO_ZIP_SELECT 1001
#define IDC_EDIT_ENCODESTR              1001
#define IDC_IP_ADDR                     1002
#define IDC_EDIT_MONSTER                1002
#define IDC_STATIC_FOLDER_TO_ZIP        1002
#define IDC_BUTTON_Make                 1002
#define IDC_PORT_NUM                    1003
#define IDC_STATIC_CHARACTER            1003
#define IDC_BUTTON_SAVE                 1003
#define IDC_EDIT_OUTPUT_FOLDER          1003
#define IDC_LIST_FILEPATH               1003
#define IDC_STATIC_MONSTER              1004
#define IDC_BUTTON_OUTPUT_FOLDER_SELECT 1004
#define IDC_BUTTON_AddFile              1004
#define IDC_STATIC_ITEM                 1005
#define IDC_STATIC_TARGET_ZIP_FOLDER    1005
#define IDC_EDIT_ITEM                   1006
#define IDC_LIST_FILE                   1006
#define IDC_BUTTON_ZIP_FOLDER           1006
#define IDC_BUTTON_Delete               1006
#define IDC_EDIT_CHARACTER              1007
#define IDC_STATIC_REINSTALL_VERSION    1007
#define IDC_STATIC_ZIP_FOLDER           1007
#define IDC_PROGRESS_MAKE               1007
#define IDC_STATIC_INT1                 1008
#define IDC_PROGRESS_GLOBAL             1008
#define IDC_CHECK_ENCODE                1008
#define IDC_EDIT_INT1                   1009
#define IDC_STATIC_PROGRESS_TEXT        1009
#define IDC_STATIC_INT2                 1010
#define IDC_EDIT_GROUPNAME              1010
#define IDC_STATIC_START_VERSION        1010
#define IDC_EDIT_TARGETDIR              1010
#define IDC_EDIT_INT2                   1011
#define IDC_STATIC_LABEL                1011
#define IDC_STATIC_END_VERSION          1011
#define IDC_STATIC_FLOAT1               1012
#define IDC_EDIT_USER_COUNT             1012
#define IDC_EDIT_START_VERSION          1012
#define IDC_EDIT_FLAOT1                 1013
#define IDC_STATIC_OUTPUT_PATH          1013
#define IDC_EDIT_END_VERSION            1013
#define IDC_STATIC_FLAOT2               1014
#define IDC_EDIT_INFO_OUTPUT_PATH       1014
#define IDC_EDIT_VERSION_LIST_FILE_NAME 1014
#define IDC_EDIT_FLOAT2                 1015
#define IDC_BUTTON_IG_MONSTER           1015
#define IDC_CHECK_USE_PREVIOUS_ZIP_FILE 1015
#define IDC_STATIC_STRING               1016
#define IDC_EDIT_FILENAME               1016
#define IDC_STATIC_INPUT_SQL_FILE       1016
#define IDC_COMBO_COMPRESS_LEVEL        1016
#define IDC_EDIT_STRING                 1017
#define IDC_EDIT_FTPIP                  1017
#define IDC_EDIT_INFO_SQL_FILE_PATH     1017
#define IDC_STATIC_COMPRESS_LEVEL       1017
#define IDC_EDIT_FTPPORT                1018
#define IDC_BUTTON_IG_ITEM              1018
#define IDC_EDIT_OUTPUT_CODE            1018
#define IDC_STATIC_VERSION_FILE_FULL_PATH 1018
#define IDC_EDIT_FTPACCOUNT             1019
#define IDC_BUTTON_IG_MAPOBJECT         1019
#define IDC_STATIC_COMMENT              1019
#define IDC_EDIT_FTPPASSWORD            1020
#define IDC_BUTTON_IG_ALL               1020
#define IDC_BUTTON_EXEC_DBOUT           1020
#define IDC_EDIT_FILENUMBER             1021
#define IDC_BUTTON_IG_QUEST             1021
#define IDC_EDIT_COMMAND                1021
#define IDC_EDIT_REINSTALL_VERSION      1022
#define IDC_BUTTON_IG_QUEST_NPC_TALK    1022
#define IDC_EDIT_DBGOUT_BIN             1022
#define IDC_STATIC_COMMAND              1023
#define IDC_BUTTON_IG_RARE_FIX          1023
#define IDC_EDIT_CMD_OUT                1025
#define IDC_CBARRAY_CHECKBOX            1027
#define IDC_COMBO_SELECT_SERVER_IP      1028
#define IDC_STATIC_NUMBER               1029
#define IDC_COMBO_SERVER_LIST           1030
#define IDC_COMBO_EVENT_TYPE            1031
#define IDC_STATIC_CURRENT              1032
#define IDC_DATEPICKER_DEFAULT          1033
#define IDC_DATEPICKER_SETTING          1034
#define IDC_TIMEPICKER_DEFAULT          1035
#define IDC_TIMEPICKER_SETTING          1036
#define IDC_EDIT_CITYWAR_MAPINDEX       1037
#define IDC_RADIO_K                     1038
#define IDC_RADIO_E                     1039
#define IDC_RADIO_J                     1040
#define IDC_RADIO_C                     1041
#define IDC_RADIO_VIT                   1043
#define IDC_EDIT_LANG_INFO              1044
#define IDC_COMBO_SERVER_SBC            1045
#define IDC_EDIT_UID_SERVER_SBC         1046
#define IDC_EXCELFILE_SEARCH            1046
#define IDC_EDIT_PWD_SERVER_SBC         1047
#define IDC_EDIT_UID_DB_SBC             1048
#define IDC_DB_TABLES                   1048
#define IDC_EDIT_PWD_DB_SBC             1049
#define IDC_INSERT_DB                   1051
#define IDC_SELECT_EXCELFILE            1052
#define IDC_EXCELFILE_TABLES            1054
#define IDC_SELECT_DB                   1056
#define IDC_RECORDPROGRESS              1057
#define IDC_TOTALPROGRESS               1058
#define IDC_TABLENAME                   1059
#define IDC_TOTAL                       1060
#define IDC_OLDDATALIST                 1062
#define IDC_NEWDATALIST                 1063
#define ID_TCM_CONNECT_FIELD            32771
#define ID_TCM_DISCONNECT_FIELD         32772
#define ID_TCM_NUM_CLIENTS_FIELD        32775
#define ID_TCM_PING_FIELD               32776
#define ID_TCM_SHUTDOWN_FIELD           32777
#define ID_TCM_PRINTMAP_FIELD           32778
#define ID_TCM_MAPBLOCKINFO_FIELD       32779
#define ID_TCM_CONNECT_NPC              32780
#define ID_TCM_PING_NPC                 32781
#define ID_TCM_DISCONNECT_NPC           32782
#define ID_TCM_MAPBLOCKINFO_NPC         32783
#define ID_TCM_PING_PRE                 32784
#define ID_TCM_CONNECT_PRE              32785
#define ID_TCM_DISCONNECT_PRE           32786
#define ID_TCM_RELOAD_VERSION_INFO_PRE  32787
#define ID_TCM_NUM_CLIENTS_PRE          32788
#define ID_TCM_PRINT_DBG                32789
#define ID_TCM_PRINTMAP_NPC             32791
#define ID_TCM_CHANGE_BANDWIDTHFLAG_PRE 32792
#define ID_TCM_CHANGE_BANDWIDTHFLAG_NPC 32793
#define ID_TCM_CHANGE_BANDWIDTHFLAG_FIELD 32794
#define ID_TCM_SHUTDOWN_PRE             32795
#define ID_TCM_CONNECT_IM               32796
#define ID_TCM_SHUTDOWN_NPC             32797
#define ID_TCM_NUM_CLIENTS_IM           32798
#define ID_TCM_PING_IM                  32799
#define ID_TCM_CHANGE_BANDWIDTHFLAG_IM  32800
#define ID_TCM_DISCONNECT_IM            32801
#define ID_TCM_SHUTDOWN_IM              32802
#define ID_TCM_PRINT_DBG_IM             32803
#define ID_TCM_SET_MSG_PRINT_LEVEL_FIELD 32804
#define ID_TCM_SET_MSG_PRINT_LEVEL_NPC  32805
#define ID_TCM_SET_MSG_PRINT_LEVEL_PRE  32806
#define ID_TCM_SET_MSG_PRINT_LEVEL_IM   32807
#define ID_TCM_GET_CHARACTER_INFO_FIELD 32808
#define ID_UPDATELIST                   32809
#define ID_TCM_PAUSE_FIELD              32810
#define ID_TCM_START_FIELD              32811
#define ID_TCM_PAUSE_PRE                32812
#define ID_TCM_START_PRE                32813
#define ID_TCM_RENAME_ROOT              32814
#define ID_TCM_DELETE_ROOT              32815
#define ID_TCM_GET_USER_COUNTS_IM       32817
#define ID_TCM_GET_USER_COUNTS_FIELD    32818
#define ID_TCM_GET_SERVER_GROUP_INFO_PRE 32819
#define ID_TCM_RELOAD_ITEM_INFO_FIELD   32820
#define ID_TCM_RESET_NPC_CONNECTION_FIELD 32821
#define ID_TCM_PRE_SET_LIMIT_USER_COUNT 32823
#define ID_TCM_GET_USER_COUNTS_NPC      32824
#define ID_TCM_NPC_SET_LIMIT_MONSTER_COUNT 32825
#define ID_INFO_GEN                     32826
#define ID_SQL_READER                   32827
#define ID_ADMIN_COMMAND_WINDOW         32828
#define ID_TOOLS_SET_NOTICE_FILE_PATH   32830
#define ID_TOOLS_STOP_NOTICE_PLAYSOUND  32831
#define ID_TCM_RELOAD_BLOCKED_ACCOUNT_PRE 32832
#define ID_CLIENT_FTP_UPDATE_MANAGER    32833
#define ID_MENU_TRAY_ACTIVE             32834
#define ID_MENU_TRAY_EXIT               32835
#define ID_TCM_RELOAD_QUEST_INFO_FIELD  32837
#define ID_TCM_FIELD_INCREASE_CHANNEL   32838
#define ID_TCM_FIELD_ENABLE_CHANNEL     32839
#define ID_TCM_FIELD_DISABLE_CHANNEL    32840
#define ID_ZIP_FILE_GEN                 32841
#define ID_TCM_GET_USER_MONSTER_COUNT   32842
#define ID_TCM_SET_MGAME_EVENT          32843
#define ID_TCM_PRE_CHANGE_ENABLE_SERVER_GROUP 32844
#define ID_TCM_FIELD_CITYWAR_CHANGE_TIME 32845
#define ID_TCM_PREPARE_SHUTDOWN         32846
#define ID_TCM3_PREPARE_SHUTDOWN        32847
#define ID_IMPORT_EXCELFILE             32848

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
