typedef union
{
	int				integer;
	char			*string;
	ITEM_W_COUNT	item_w_count;
	INT_RANGE		integer_range;
} YYSTYPE;
#define	QUEST_TOK	258
#define	BASIC_INFO_TOK	259
#define	QUEST_INDEX_TOK	260
#define	QUEST_NAME_TOK	261
#define	QUEST_TYPE_TOK	262
#define	QUEST_START_TYPE_TOK	263
#define	QUEST_END_TYPE_TOK	264
#define	NPC_INDEX_TOK	265
#define	NPC_NAME_TOK	266
#define	PRE_TALK_TOK	267
#define	FAIL_TALK_TOK	268
#define	SUCCESS_TALK_TOK	269
#define	NEXT_QUEST_INDEX_TOK	270
#define	START_REQ_TOK	271
#define	S_REQ_UNIT_KIND_TOK	272
#define	S_REQ_LEVEL_TOK	273
#define	S_REQ_ATTACK_PART_TOK	274
#define	S_REQ_ENDURANCE_PART_TOK	275
#define	S_REQ_FUEL_PART_TOK	276
#define	S_REQ_SOUL_PART_TOK	277
#define	S_REQ_DEFENSE_PART_TOK	278
#define	S_REQ_DODGE_PART_TOK	279
#define	S_REQ_ITEM_TOK	280
#define	S_REQ_QUEST_INDEX_TOK	281
#define	START_ACTION_TOK	282
#define	S_PAY_ITEM_TOK	283
#define	S_DEL_ITEM_TOK	284
#define	COMPLETION_REQ_TOK	285
#define	C_REQ_MEET_NPC_INDEX_TOK	286
#define	C_REQ_ITEM_TOK	287
#define	COMPLETION_ACTION_TOK	288
#define	C_PAY_BONUS_STAT_TOK	289
#define	C_PAY_BONUS_SKILL_POINT_TOK	290
#define	C_PAY_FAME_TOK	291
#define	C_PAY_STATUS_TOK	292
#define	C_PAY_LEVEL_TOK	293
#define	C_PAY_EXPERIENCE_TOK	294
#define	C_PAY_WARP_MAP_INDEX_TOK	295
#define	C_DEL_ITEM_TOK	296
#define	C_PAY_ITEM_TOK	297
#define	FROM_TOK	298
#define	MONSTER_TOK	299
#define	ALL_TOK	300
#define	GT_TOK	301
#define	LT_TOK	302
#define	GE_TOK	303
#define	LE_TOK	304
#define	EQUAL_TOK	305
#define	USER_VARIABLE_TOK	306
#define	INTEGER_TOK	307
#define	WORD_TOK	308
#define	QSTRING_TOK	309


extern YYSTYPE QuestLoaderlval;
